### ISSUE TITLE
Blog post tags are case sensitive

### ISSUE THREAD

**Issue by siboehm** [PanosSakkos/personal-jekyll-theme#213]
When using tags in a blog post, the tag has to be all lowercase or it will result in broken links.

## To reproduce
1. Create a new blog post, set `tags: ['CamelCase']`.
2. Run the script to create the tag-subpages: `./scripts/generate-tags`.
3. Now the link on the tag will point to `/tags/CamelCase.html`, but the subpage created is located at `/tags/camelcase.html` so you will get the 404 page.

It is confusing that the tags have to be all lowercase, I suggest naming the subpages exactly the same as the tag that created them

**Comment by eiselems** [comment]
Maybe it is better to discuss the issue here and not in the PR. 

The result of this is that there can be multiple tags like 'tutorials' 'Tutorials' 'TuTorials'. I wouldn't mind to have lower-case only tags - so I think we could adjust the link generation inside the pages to create the correct lowercase links. 

The only downside  would be having no tags with proper uppercased letters.  
@PanosSakkos any preference?

**Comment by joariasl** [comment]
It's more efficient using a JavaScript validation before return the 404 error code, but only for the tags path.

**Comment by siboehm** [comment]
@joariasl What do you mean by JavaScript validation?

@eiselems I agree, having all tag-pages lowercase makes more sense and is less confusing. For posts, the tags are displayed in all uppercase anyway, so you wouldn't see the difference between different 'versions' of the same tag. 

I will amend the pull request.

**Comment by joariasl** [comment]
@siboehm I meant to check the URL path in the request from JavaScript for redirect to lowercase.

**Comment by eiselems** [comment]
Wasn't aware that everything is in uppercase anyway.
I just would suggest to create the link hrefs in lowercase letters and also generate lowercase pages for the tags.
